---
- name: Download kubectl binary
  ansible.builtin.get_url:
    url: https://dl.k8s.io/release/v1.27.3/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'

- name: Ensure kubectl is executable
  ansible.builtin.file:
    path: /usr/local/bin/kubectl
    mode: '0755'

- name: Check kubectl version
  ansible.builtin.command: kubectl version --client --short
  register: kubectl_version
  changed_when: false

- debug:
    var: kubectl_version.stdout

